version: '3'
services:
  gateway:
    image: gateway:1.0
    ports:
      - 4000:4000
    environment:
      - ASSET_SERVICE_URL=http://host.docker.internal:3000
  asset-service:
    image: asset-service:1.0
    ports:
      - 3000:8080
